### ISSUE TITLE
New data always overwrites previous data

### ISSUE THREAD

**Issue by Gitoffthelawn** [wildskyf/TextareaCache#10]
TACL v1.3.2, Firefox v53.0

Only saves the last text from the field, even though there is a drop-down within the extension's UI indicating that it should be storing previous entries as well.

IOW, when new text is entered, it overwrites the previously saved text.

**Comment by wildskyf** [comment]
Hi @Gitoffthelawn,

It is good to hear your report,
I will add this feature back. (Maybe on this weekend.)

**Comment by Gitoffthelawn** [comment]
Thanks!  I look forward to it! :)

**Comment by wildskyf** [comment]
Hi @Gitoffthelawn 

I have update textarea cache lite to 2.0.1,
It will save data using `Date + Document Title + serial` no in the pages as its key.

So if you save text today & yesterday, TCL will save both of them.
I will provide an option for users to decide the frequency. (now is one save one date)

If you test it and I does work for you, you could just close this issue. :)
And I will open another issue for the option I mentioned above.

**Comment by Gitoffthelawn** [comment]
Thanks. :-)

More than 1 per date will be important.

What is `serial`... is it random?

Did you move the icon out of the urlbar and into the toolbar in v2.0.1?

**Comment by wildskyf** [comment]
> What is serial... is it random?

The first textarea, the second textarea, ... etc. Isn't it called serial no? :P (idk how to call it)

> Did you move the icon out of the urlbar and into the toolbar in v2.0.1?

yes, do you think using page action is better?
Or should it be an option for users?

**Comment by Gitoffthelawn** [comment]
> The first textarea, the second textarea, ... etc. Isn't it called serial no? :P (idk how to call it)
LOL.  WFM now that I know what you mean! :P

> yes, do you think using page action is better?
Or should it be an option for users?

I liked the page action more, but I think some might prefer a toolbar button... an option for users will be ideal.

BTW, not related to any of the above, you might want to check out Form Save at https://github.com/lutostag/webextension-formsave/  .   It is a similar extension with a nice UI.  The author is waiting for a new version to be approved by Mozilla, but Mozilla is slow.

**Comment by wildskyf** [comment]
Hi Gitoffthelawn,

> I liked the page action more, but I think some might prefer a toolbar button... an option for users will be ideal.

okay, I will add an option in the future. (ref #15)

> BTW, not related to any of the above, you might want to check out Form Save at https://github.com/lutostag/webextension-formsave/ . It is a similar extension with a nice UI. The author is waiting for a new version to be approved by Mozilla, but Mozilla is slow.

Thank you a lot!! That is a good reference for me. :)

**Comment by Gitoffthelawn** [comment]
Thanks... and... you're welcome! :-)

**Comment by ceribik** [comment]
> So if you save text today & yesterday, TCL will save both of them.
I will provide an option for users to decide the frequency. (now is one save one date)

Isn't that kind of pointless? I ran into this quirk today after writing a long post. I accidentally went to another page, and the form was reset to blank. However, because I pressed a key it overwrote the saved text in your addon.

The current fix won't solve this issue. With lazarus form recovery (pre-webextension), it just saved as many copies of the textarea as you created.

**Comment by wildskyf** [comment]
Hi @Gitoffthelawn @ceribik,

I have changed the timing of saving new data, which won't be overwritten by previous data, from date to session, which means you will start another cache every time you open a website.

I think it is more useful than the origin rule.

**Comment by wildskyf** [comment]
ok, I think current status is good, so let's close this issue!
