### ISSUE TITLE
Removed from the Chrome store due to malware

### ISSUE THREAD

**Issue by HyphenSam** [wildskyf/TextareaCache#105]
"This extension has been turned off as it's been marked unsafe by the Chrome Web Store."

[The Chrome Store link](https://chrome.google.com/webstore/detail/chpphekfimlabghbdankokcohcmnbmab) returns a 404.

**Edit:** Issue is mostly resolved, but is currently not working for Edge users.

**Comment by wildskyf** [comment]
Hi @HyphenSam @bsiegel & @jasonhsutuna ,

I have removed useless permission `tabs` and submitted a new version to chrome store.
Textarea Cache will be back soon.

**Comment by vsrawat** [comment]
I had also been facing the same problem for some 3-4 days. I wrote email to the developer and he guided me to this thread.

So, please add my name also in the people affected.

Glad to see prompt action by the developer to resolve the issue.

Thanks.

**Comment by Gitoffthelawn** [comment]
Why is this issue report entitled "Removed from the Chrome store due to malware"?

A single unneeded permission in the manifest is hardly malware.

Does someone have any evidence that there is any malware at all in this very useful (and open source) tool?  Did Google make a claim about malware?  If neither of these are true, I think the OP owes the generous and talented author a sincere apology and retraction.

**Comment by wildskyf** [comment]
@Gitoffthelawn  Thank you, but the "malware" term is used by google, not the OP.
So OP does not owe me any apology, maybe google does. 😆 

And here we have a good news: Textarea Cache is back to Chrome Store!
https://chrome.google.com/webstore/detail/textarea-cache/chpphekfimlabghbdankokcohcmnbmab

Thank you all :)

**Comment by HyphenSam** [comment]
@wildskyf Thanks, was about to write a response, but glad you've cleared any misunderstandings. Closing this because the issue has been solved.

**Comment by Gitoffthelawn** [comment]
@wildskyf Yes, if Google used the term "malware", they definitely owe you an apology (and a bunch of other people too).  Where exactly did they use that term?  Can you post a link and/or a screenshot?

It will make a handy reference so we can all call Google Chrome (and many other Google products) "malware" as they have much greater issues than an unused permission in a manifest file!

@HyphenSam I'm glad this was cleared up quickly too! 👍🏾

**Comment by vsrawat** [comment]
> I had also been facing the same problem for some 3-4 days. I wrote email to the developer and he guided me to this thread.
> 
> So, please add my name also in the people affected.
> 
> Glad to see prompt action by the developer to resolve the issue.
> 
> Thanks.

 Textarea Cache is back on Google Web store.

However, Edge has no button or setting for updating the add-on manually. It does so automatically as and when it wishes. And as  Textarea Cache has been disabled by Edge, there is no way you can enable or update it.

If you go to Google Web store and try to install it again, it says, "error downloading" or something.

What you have to do is to remove the addon from Edge extensions page, then go to Google Web store, and install  Textarea Cache afresh. That would make you earlier customization gone, I guess, so put the settings again.

I have uninstalled and reinstalled it and it is working again.

Thanks a lot.

**Comment by HyphenSam** [comment]
@vsrawat I'm using Edge and have the same issue. It's weird how uninstalling and reinstalling works for you, but not for me. I even tried restarting the browser before reinstalling, and manually updating extensions with "Developer mode" enabled. Right now it's showing up as version 4.5.0.
I installed this extension on Brave and it works fine there, so it's clearly an Edge issue.

I've contacted Edge Insider Support and they said they'll "report this to the extension team."

**Comment by vsrawat** [comment]
You are right.

Once I had gone through uninstall-install, the addon was showing as 
active in my Edge extensions page, (first pic) so I thought it had 
started working correctly.

But after some time, it again gave that error message (second pic). You 
can see in the pic that it is new version of the addon.

And then onwards the extension remains disabled, as in third pic.

You can see in the fourth pic that it is the new version of the 
extension, but it is still disabled.

But, previously, Chrome web store page of the addon was throwing 404, 
now, with the new version, Chrome web store page is appearing active, so 
Google has rectified their mistake.

I don't know but it seems that google removing the malware tag has yet 
to reach Edge's database through some ripple or cache effect. I don't 
know when and if that would happen.

Seems the developer would not be able to help now. This now has reached 
Cyberverse dynamics stage.

Thanks.
-- 
Rawat

**Comment by wildskyf** [comment]
Yes, I found that edge still has problem, too... I have submit a temporary version Textarea Cache to Edge store.
(Might not as stable as chrome & firefox version but work) Now we have to wait for the review and publish...

Here is the review submission screenshot:
<img width="739" alt="截圖 2022-07-14 13 04 00" src="https://user-images.githubusercontent.com/6042803/178903209-7f2bec1c-a60d-41cb-930c-dae8cc07fa31.png">

And the source of the temporary version is at the branch: [wildskyf/TextareaCache/quickfix-for-edge](https://github.com/wildskyf/TextareaCache/tree/quickfix-for-edge)

Once the review pass and Textarea Cache is published on Edge Store, I will notify your guys here.
Sorry for the inconvenient.

**Comment by HyphenSam** [comment]
Microsoft Edge Insider Support just responded today saying this extension can now be used in Edge. I installed it now and it works fine. Looks like my settings and history was cleared, but I clear my history regularly so it doesn't matter to me.

@vsrawat can you install and see if it works for you too? If it does, we can close this issue.

**Comment by vsrawat** [comment]
I also confirm that today onwards the extension is working well in Edge. 
Till yesterday it was giving that malware warning and was disabling.

I didn't do anything about it yesterday and today, seems edge's setting 
itself removed that malware tag and it is fine again.

My old data is intact, but only after the point when I had repeatedly 
uninstalled and reinstalled it from google web store. The data before 
uninstalling is gone, but some 5 days data is still there, even while 
the extension was "not supposed to be working" in Egde. :-) Seems it was 
working all the time behind the scenes but Edge marked as non-working.

Thanks.
-- 
Rawat
