### ISSUE TITLE
Update "Developer comments" on AMO to reflect correct GitHub userid

### ISSUE THREAD

**Issue by Gitoffthelawn** [wildskyf/TextareaCache#107]
The [AMO page](https://addons.mozilla.org/firefox/addon/textarea-cache/) currently lists your old GitHub username (ettoolong) in the link in the "Developer comments" section.  It would be good to update that link to reflect your current GitHub username (wildskyf).

**Comment by wildskyf** [comment]
done, and thanks :)

**Comment by Gitoffthelawn** [comment]
You're welcome.  Verified the update on AMO.  Looks good.

**Comment by Gitoffthelawn** [comment]
BTW, I noticed https://ettoolong.github.io/test/textarea.html still works without redirection.  Any idea why?
