### ISSUE TITLE
Source of fork merge

### ISSUE THREAD

**Issue by Gitoffthelawn** [wildskyf/TextareaCache#133]
It appears that the source code was recently updated with that of a fork, but I'm not seeing the history of that fork.  Which fork was the source of that merge, and where is its history?  Are there pull requests for each change somewhere?  I would like to review all the individual changes in addition to comparing the comprehensive final resultant releases.

Also, can the releases page on GitHub be updated with the new release when you get a chance?

Thanks for keeping this updated.

**Comment by crnkv** [comment]
https://github.com/GHolk/TextareaCache/tree/tcm
This, I think, although that fork is maintained under the name "Textarea Cache M" version 4.9.0 (as reflected in its manifest.json and README.md), meaning what's now in wildskyf/TextareaCache version 4.9.1 might be slightly different

**Comment by GHolk** [comment]
crnkv is right, its last commit was d0c8be488c637834ad6822ea2b5dafcc6576880b .
I squash all the commits in the fork since its history is a little messy.
I also delete the **textarea cache m** on AMO since it was merged.

@wildskyf invited me to maintain this addon. I will work on TextareaCache directly from now on.

**Comment by GHolk** [comment]
About the release, you can download the signed XPI file on AMO,
and XPI without signature can not be installed for most firefox user.
Can you say more about this?

**Comment by Gitoffthelawn** [comment]
> About the release, you can download the signed XPI file on AMO, and XPI without signature can not be installed for most firefox user. Can you say more about this?

Sorry for the delay in my response.  I'm catching up on my GitHub notifications.

Ideally, in addition to AMO, the current XPI and source will also be available on:  
https://github.com/wildskyf/TextareaCache/releases

Kindly notice that page hasn't been updated in about 7-8 years.

**Comment by GHolk** [comment]
inactive
