### ISSUE TITLE
Delete not working correctly

### ISSUE THREAD

**Issue by Gitoffthelawn** [wildskyf/TextareaCache#16]
Version 2.2.0 is a huge improvement!  Thanks!

It is not deleting items correctly, however.  I deleted the storage file to start over, but delete is still having issues.  Deleting the last item is not possible.

Thanks again for the great extension... it's coming along nicely.

**Comment by wildskyf** [comment]
Thank you for your encouragement and bug report. :)
Users' reports means a lot to me. I will try my best to make this add-on better and better!

**Comment by Gitoffthelawn** [comment]
You're welcome... and thank YOU!

**Comment by wildskyf** [comment]
@Gitoffthelawn Is it work correctly now? If the answer is yes, we could close this issue. :)

**Comment by Gitoffthelawn** [comment]
It seems to be working.  I'll re-open if I notice any issues with the delete functionality.

**Comment by bendover22** [comment]
Today is the 1st time I tried deleting any entries.  It's not deleting any for me.
TAC 3.13.0, Using Fx 52.5.3 esr in Mint 18.1 64 bit.
Select 3 or  4 consecutive entries - showing on the monitor.  Delete Selected Cache doesn't work.
Select 10 or 15 consecutive entries - won't delete.
Select some entries w/ "Invalid Date" - won't delete.
Select some entries w/ proper dates - won't delete.

**Comment by wildskyf** [comment]
@benddover22 @gitoffthelawn do you still have problem when you are deleting cache? (with the latest Textarea cache?)

**Comment by Gitoffthelawn** [comment]
@wildskyf It works for me, but it sounds like @bendover22 might be having an issue.

**Comment by wildskyf** [comment]
@bendover22 If you still have problem about this issue, feel free to open and comment!

**Comment by bendover22** [comment]
> do you still have problem when you are deleting cache? (with the latest Textarea cache?)

Not sure.  What's the latest version? :)  If it seems like a good idea, when a problem / attempted fix spans several releases, we could all state which version specific comments apply to?

I see in v3.15, it seems to correctly delete selected entries (limited testing).

Only now (3.15) EVERY entry has changed to show the same time stamp 1/26/2018, 1:28:27 PM.
But they were created over days or weeks, not one day.  

Haven't tried 3.17 yet - I will now.
Only thing in 3.17 release notes (in Addons Manager) I see is, "correct I18n for zh_CN."  Was that the only change?

Question:  are there more detailed release notes, that would show up 1) on Github 2) in Fx Addons Manager release notes 3) contained in a release notes / change log file, inside the installed xpi?  

I see very few of changes being made (discussed in this issues section) that are listed in the installed versions Readme.  Unless mine is the only one not showing these, Can't tell if changes in a version are working if we don't know what changes were included in the version.

**Comment by wildskyf** [comment]
Hi @bendover22 

> Only now (3.15) EVERY entry has changed to show the same time stamp 1/26/2018, 1:28:27 PM.
But they were created over days or weeks, not one day.

yeah, it is a known issue, we could discuss it at #67.

> Question: are there more detailed release notes, that would show up 1) on Github 2) in Fx Addons Manager release notes 3) contained in a release notes / change log file, inside the installed xpi?

You might need this: <https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/versions/>
I currently use this page as the changelog of Textarea Cache. I will add it to readme later so that you could easily access this page.
