### ISSUE TITLE
add some feature into right click textareas

### ISSUE THREAD

**Issue by ceribik** [wildskyf/TextareaCache#33]
It would be nice to be able to right click textareas and show a list of clickable saves of that text area.

See:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Context_menu_items
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/create
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/ContextType

**Comment by wildskyf** [comment]
Hi @ceribik 
I have implemented it in the version 3.12.0, you could try it. :)
If you think the confirmation message is really annoying, you could go to option page of Textarea Cache and check `Skip Confirm When Paste From Context Menu`

If you have any other problem, feel free to reopen this issue or open another one.

**Comment by lilydjwg** [comment]
I don't like this one. It makes my context menu very wide.

**Comment by wildskyf** [comment]
@lilydjwg  Oh... I forgot to add an option for it.
I will add it this weekend!

**Comment by wildskyf** [comment]
@lilydjwg I have added the option for disabling this feature.
I should be 'enable context menu' by default.
Feel free to uncheck it in the preference page.

**Comment by wildskyf** [comment]
ref #66

**Comment by lilydjwg** [comment]
I see 👍
