### ISSUE TITLE
Care2

### ISSUE THREAD

**Issue by mcaustinsr** [wildskyf/TextareaCache#34]
I tried this on Care2 with no joy.  I was testing the add-on.  I opened a new post, typed 2 sentences and then closed the tab.  I then opened a new tab, logged back in and went back into the group to answer the post I tried to answer before.  I opened a new post and clicked the TextArea icon.  It was empty.  
 
My main reason for needing this add-on, about 99.9%, is for work on Care2.  Since Lazarus doesn't work anymore, I need to find a replacement.  I'm hoping this tool will be it.  I'm happy to do any beta testing for you!

**Comment by wildskyf** [comment]
ok, I will fix it in the next version.
Please be patient, thank you. :)

**Comment by wildskyf** [comment]
@mcaustinsr
Could you please check whether you have the latest version of textarea cache, and then try again?

**Comment by wildskyf** [comment]
ping @mcaustinsr again

**Comment by wildskyf** [comment]
I think it works now if you still have any problem, feel free to reopen this issue.
