### ISSUE TITLE
Not saving text fields on certain sites

### ISSUE THREAD

**Issue by bendover22** [wildskyf/TextareaCache#35]
It doesn't happen often, but again tonight I was logged into an account at Capital One Banking site https://www.capitalone.com/.
Viewing a monthly statement online, there are '+' signs beside each entry.  If clicked, brings up a text box to choose a subject (from a list), then a regular text box.  No WYSIWYG or any formatting  - plain text.

If there's anything you want me to check on the Cap One site (inside my acct), I'll see.  They may have a public "contact us" web form.  No way of knowing if both use the same method to send them a message.  I'll just have to start typing in a text editor or word processor.  My hands hurt like hell most the time.  

 I retyped the message in a text editor then C & P'd it.  Don't know if TAC will save messages pasted into the text field? 

Of course, when I was typing the last sentence, the bank's popup "you will be disconnected in XX seconds unless you click Continue," appeared and just flat closed that text box & lost the message.  
I looked to see what else was in TAC & saw a different bank (credit union) that TAC saved the internal  text message I sent them on 10/20/2017.  Very similar to the Cap One, except I didn't have to click a + sign to open a text box.  

But the message at Cap One *was* automatically saved in their message center (like internal email). Again, just plain text - no formatting available.  They saved it but TAC couldn't for some reason.

Since there's no settings for anything about disk space to allow TAC or time to keep messages, I assume it eventually fills up & deletes oldest entries to make room for new?  It looks like TAC has about 30 messages saved.  Most were very short.  I'd be surprised if they took over a few MB.

**Comment by wildskyf** [comment]
Hi @bendover22,

Could you test it again and make sure this problem still happen? By the way, please provide the version of your Textarea Cache and the OS you use so that I could debug easier. :)

**Comment by bendover22** [comment]
I commented under this issue https://github.com/wildskyf/TextareaCache/issues/29,
it shows "9 days ago."  TACL was updated on Nov 7, so I'm not sure if that was just before or after I updated to 2.11.1?

The issue listed above & this one may be basically the same.  A few minutes ago, I commented on a different Github project.  TACL didn't save any of that.
When I started typing on this reply (here), TACL didn't store anything or create an entry for this comment.  I checked after typing the 1st paragraph (..."updated to 2.11.1).
I checked uBlock Origin (now 1.14.18) & removed / disabled blocking "remote fonts".
At the lower, right of uBo's drop UI, the letter 'A' signifies remote fonts.  If it has a red 'X' over it, remote fonts are being blocked.  
I removed the X, to allow remote fonts & TACL immediately created an entry for this comment, and picked up what I'd already typed, to the beginning of this reply.

I've learned there are (at least) 2 types of remote fonts.  One is type face fonts, we normally think of.  The other is "icon fonts" or glyphs, that can be all sorts of buttons & elements. https://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/
 I don't know which type is causing TACL not to save on this site.  Or, it could be either, depending on how a site is set up, or even which 3rd party the remote fonts come from.
We might be able to tell which type font it is, as in Firefox about:config, 
browser.display.use_document_fonts controls **"regular" fonts** (0= block, 1=allow).
gfx.downloadable_fonts.enabled controls **icon fonts** (true=allow, false=block)

I don't believe uBo distinguishes between the 2 font types.  It appears to block all or allow all.
But maybe you can see something in TACL code (or the API(s) used), if it needs or uses "regular" remote fonts or icon fonts, or both. 

In my about:config, when I set "browser.display.use_document_fonts" =0, TACL kept recording typing.  First, I cleared Fx cache & reloaded this page.
Cleared cache again.  In about:config, I set "gfx.downloadable_fonts.enabled" to false, and left "browser.display.use_document_fonts" =0, then reloaded this page, but TACL kept on saving. 
Not to be made a fool, I tried restarting Fx; left both prefs disabled (no fonts) &  uBo was reset to block remote fonts.  But TACL kept on saving the text.

Clearly, there's something else.  Because when I came to Github tonight, TACL wasn't recording anything - on 2 Github pages.  In uBo, I **allowed** remote fonts & TACL **immediately** starts saving.  But when I reverse settings, even restart Fx to make TACL stop recording, I can't do it.  uBo's setting is to block remote fonts, but TACL is still saving.  

I'll try again t'mrw, after cold booting the computer.  No idea why that'd matter, but there's some reason for inconsistent results.
And, there are other sites where it didn't save (recently), but I didn't realize it until I left some of those sites.  By the way, how much does this pay?  What?  The same as you make?!?

**Comment by bendover22** [comment]
I tried again today - before & after updating TACL to 2.13.0.  
What seems to happen is, on the initial visit to a site - that day, if remote fonts are being blocked by uBo, then TACL often doesn't save anything - UNTIL I disable ***per site*** blocking of remote fonts in uBo's UI.
"Most" of the time, once I disable remote font blocking for a  site, TACL starts saving.
But that process isn't reversible - not on the same day (it appears).  If remote font blocking is **re-enabled**, it doesn't stop TACL from recording - on THAT site, though logically it should prevent TACL from further recording.  When I go to another new site & remote font blocking is on, TACL won't record until I manually disable it.  Obviously, not all sites use remote fonts, related to any text fields.

I'm guessing  that **re-enabling** remote font blocking having no affect on the current site, could be related to the ublockO.sqlite DB in the Fx profile & how (or if, when) the uBo settings for individual sites are updated in ublockO.sqlite.   Not sure.  Maybe you can figure out what blocking (any) remote fonts has to do with TACL saving plain text.

 I either need to update DB Browser for Sqlite, or get another sqlite viewer, that works in Fx 56..x.
There's also a large 14 MB storage.js for uBo.

BTW, in TACL 2.13, **the order of saved texts are now from oldest (at top) to newest.**  When you 1st click TACL icon, the oldest stored entry pops up, not the one for current site (if you're typing in a form).  When you click the arrow to show all saved entries, oldest are at the top.  Shouldn't if be the reverse - like it was before?

**Comment by wildskyf** [comment]
Hi @bendover22,

> in TACL 2.13, the order of saved texts are now from oldest (at top) to newest

That's my fault, I added `last_modified` attr into db, and sort by it. But I forgot there is some data without `last_modified`, so ... that's the problem. I have submitted a new version 2.13.1. Thank you for your report!!

and... the blocked font problem is weird, it should not work like that. Could you help me do some things?

1. Go to option page of Textarea Cache
2. open Web Console (via ctrl + shift + i)
3. open Browser Console (via ctrl + shift + j)
4. let me know what your Textarea Cache said
5. and tell me what you do step by step

I will also try it myself when I have time. Thanks again for your report, your description is really detailed!

**Comment by bendover22** [comment]
Can you explain what you're looking for - what I should be copying from the consoles?
Don't the browser & web console need to be running before starting an addon or loading pages, etc?
Also, what's TACL's debug mode?

FYI - I tried out the web ext Form History Control, but I couldn't get it to save anything, with remote fonts blocked or not.  Maybe the dev can shed some light what's happening & maybe I can test if it saves text w/ remote fonts blocked.  Uninstalled it.

The legacy FHC 1.4.0.6 works great in Fx 56.0.2 - even when blocking remote fonts.  That only helps if you stay on an Fx ESR version.

**Comment by wildskyf** [comment]
What I want to know is whether there is any error cause js stop execute.

debug mode is here:

![option list](https://user-images.githubusercontent.com/6042803/32981600-9b214c48-ccb2-11e7-8549-f5b3e3f242e7.png)
![textarea cache in about:addons](https://user-images.githubusercontent.com/6042803/32981601-9b4d3718-ccb2-11e7-9e86-b4250fb8db15.png)
![options of textarea cache](https://user-images.githubusercontent.com/6042803/32981602-9b7645cc-ccb2-11e7-8122-b32172e20151.png)

It will print some information to console and we could see where it stop to execute if any.

**Comment by wildskyf** [comment]
by the way, I think this issue is duplicate with #29, so let's discuss there.
