### ISSUE TITLE
Icon on locationbar

### ISSUE THREAD

**Issue by rayman89** [wildskyf/TextareaCache#40]
Whatis the icon supposed to do? Clicking on it does nothing ofr me and right clicking only shows the option to take it off.

**Comment by wildskyf** [comment]
> it does nothing for me

Doesn't it pop up a list for you? If it didn't show, there might be some bugs... Let's me check it.

> What is the icon supposed to do?

It should do what browser_action button could do, which is pop up a panel listing all your cache.

you could turn it off at the options page of the Textarea Cache.

**Comment by rayman89** [comment]
Previously it always stayed greyed out for me this update made it work on some pages and not appear on the rest. For example on this exact page this is how it shows.

![imagen](https://user-images.githubusercontent.com/5449042/32956162-f214bb4c-cbaf-11e7-9960-72c62c65a7c4.png)

but on this page with no text at all it shows and functions when clicked 

![imagen](https://user-images.githubusercontent.com/5449042/32956194-0d84188c-cbb0-11e7-86c8-0482fda9d7d7.png)

BTW I'm using firefox 58 beta dev edition

**Comment by wildskyf** [comment]
> but on this page with no text at all it shows and functions when clicked

In the current version, it supposed to appear on pages in which there is some textarea.
But in fact, some pages will use invisible elements to something, and somehow it will match my saving rules. So you would see it appear on pages in which there is no text content to save. It won't be fixed, but it is not a big deal in my opinion.

By the way, do you think appearing on every page is better?

**Comment by rayman89** [comment]
I do think appearing in every page is better because like my screenshot shows it's not appearing in github  where it's needed but it's appearing on a page that only has a video player so to avoid detection problems and have consistency I think it might be better to just appear on every page.

**Comment by wildskyf** [comment]
ok, I will change it to appear at every page in the next version.

**Comment by wildskyf** [comment]
It will show on ever page after v2.14.0 now. :)
