### ISSUE TITLE
Sort by Date in popup is wrong

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/TextareaCache#44]

**Comment by wildskyf** [comment]
Finally fixed @ v2.13.2.

**Comment by wildskyf** [comment]
wrong again....

**Comment by wildskyf** [comment]
it should be right in the v3.4.1

**Comment by bendover22** [comment]
What am I missing?  In TAC 3.13, I don't see any way to sort text entries - anywhere.
Not from the toolbar icon; not R-clicking the saved data screen; not from Addons Manager prefs.
In v3.13, is there supposed to be some sorting feature?
