### ISSUE TITLE
improve the cache list UI

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/TextareaCache#45]
as @bendover22 said:

> as of v2.3 there's still no way to select multiple entries at once in the drop list to delete them.
> AFAIK, only one entry can be selected - to show in TACL's display, before you can delete it.
> 
> That's fine for 1 or 2 entries. Very tedious for 10+, deleting one at a time. That's assuming user doesn't want to "delete all cache."
> 
> I'm not sure how hard it'd be to add the option to select a continuous block of entries (e.g., Shift + click), or to select several non-adjacent entries (e.g., Ctrl + click - random entries), then delete selected items at once.

**Comment by Gitoffthelawn** [comment]
I would like to see an option to clear the textarea cache when the browser is closed (assuming it didn't close due to a crash).  That way, the list never gets too long.  I don't think I've ever needed to recover text from a previous browser session.

**Comment by wildskyf** [comment]
@Gitoffthelawn yes, that is the #21 😉

**Comment by Gitoffthelawn** [comment]
Doh!  Forgot about that issue!

**Comment by wildskyf** [comment]
Here is the struct of the list of new UI

Features: 
- click `checkbox` in the title field allow you to select all items
- click attr titles (`URL`, `summary`, `date`) will sort items by that attr
- click URL in each item will open that URL
- click summary or date in each item will open the page in which there are the old UI (or maybe better)
- you can filter the result by using the search bar
- the `?` button will tell you how to filter

Maybe I will add a button after Date, and just click you could go to the old UI or maybe copy the cache directly.

![2017-11-20 17-40-15](https://user-images.githubusercontent.com/6042803/33011780-ea269524-ce19-11e7-951a-42e5412fb644.png)

**Comment by Gitoffthelawn** [comment]
Maybe for the date, remove the timezone.

**Comment by wildskyf** [comment]
yeah, I will use local string for it
it will be released tomorrow

I want it could be released today, but i found some bugs, so immediately
disable the v3.0.0... I will try to fix those bugs when tomorrow I wake up

2017年11月21日 01:39，"Gitoffthelawn" <notifications@github.com>寫道：
