### ISSUE TITLE
New UI renders the add-on totally useless

### ISSUE THREAD

**Issue by drcheap** [wildskyf/TextareaCache#46]
* System OS: Windows 7
* Firefox version: Firefox 57.0
* TCL version: ?

Steps to reproduce:
* Click toolbar icon, view listing, click show button...nothing happens

(this is after clicking show)
![image](https://user-images.githubusercontent.com/10265909/33058704-7d3066a6-ce56-11e7-9998-c40817c2a914.png)

I did see in v3.0.1 that there is supposed to be another section at the bottom with the full text, and a couple of buttons, but that is totally gone now in v3.0.5.  Furthermore, even in v3.0.1 the full text box was always blank for me, and so clicking Copy didn't ever put anything on my clipboard.

Also, in the new UI, the most important thing (the cached text!!) is given very little screen real-estate.  I realize that it's still a bit of a work in progress in this respect, so I would like to offer some suggestions.  The summary should be the widest, maybe shorten the URL (hostname only?) or wrap the date value so the time is on a 2nd line to make more room for a wider summary column, which could also show amount of characters.

P.S. I **love** this add-on, and have been using it for many years.  Very happy to see the active development on the WebExtensions version, keep up the good work!

**Comment by wildskyf** [comment]
Sorry about that, there are some bugs, and I am going to fix it today.
btw, The latest version is v3.0.5 (but there are still some bugs... Orz

Thank you for your love! I will make this add-on better and better!!!

**Comment by wildskyf** [comment]
@drcheap It should work now, try v3.1.0 [here](https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/)!

**Comment by drcheap** [comment]
Awesome!  Love the new column sizing & more importantly the functioning show & copy buttons.

Summary text still truncated after a few words, but not a showstopper (you are probably still working on that).

**Comment by wildskyf** [comment]
haha, I will keep tunning it, but I still think about the situation that user might also save Chinese words, which means it might break the layout if truncated after too more words...

but anyway, let's close this issue now, feel free to reopen if you still have any problem :)
