### ISSUE TITLE
Recent versions make firefox use 10x ram and hang after restoring session

### ISSUE THREAD

**Issue by dequis** [wildskyf/TextareaCache#47]
Required:
* System OS: Arch Linux
* Firefox version: Firefox 52.5.0
* TCL version: 3.1.0 and 2.14.0 (last known good: 2.5.0)

Optional:
* Steps to reproduce:
    * Install [session manager addon](https://addons.mozilla.org/en-US/firefox/addon/session-manager/)
    * Open a few hundred tabs (i have ~700 here)
    * Save
    * Restart
    * Restore session

And you get massive ram usage (i have 24gb total, firefox used 18gb, without this addon it uses 1.2gb) and it's almost impossible to interact with the firefox UI - things render (it doesn't keep the window blank after switching, it redraws), but clicking UI items doesn't seem to do anything, right-clicking brings up context menus but that's about it. Attaching gdb suggests it spends a lot of time on javascript garbage collection.

Disabling this extension or going back to version 2.5.0 seems to fix it for me. That's the version I was using the last time I've been on this computer a month ago.

I also tried downgrading to 2.14.0 as an intermediate step, which is also affected.

The session manager addon is probably not needed, but it has the neat property of being able to save sessions by name and not restore them sometimes, allowing me to tinker with addons to be able to find that it was this one messing things up.

**Comment by dequis** [comment]
Spent a while testing versions in the middle, last good 2.13.2, first bad 2.14.0

https://github.com/wildskyf/TextareaCache/commit/180fe0ef2dd2aed50557b87a28b64168d16242b7 ?

**Comment by wildskyf** [comment]
@dequis thanks for your report, I will check it later.

**Comment by wildskyf** [comment]
Hi @dequis,
Could you please help me to check whether this problem got solved?
The latest version is v3.3.0

**Comment by dequis** [comment]
Yep, that looks way better, thanks for the quick fix!

**Comment by wildskyf** [comment]
If you found other performance issues, feel free to tell me or even how to fix it. :)
