### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by rayman89** [wildskyf/TextareaCache#48]
I noticed the new GUI change which is great but reduces the dynamicity the other GUI had so I was wondering if it would be possible to keep for the URL icon the old GUI to be able to quickly get what you want and make the button show the more detailed GUI.

**Comment by wildskyf** [comment]
what do you mean dynamicity?
Does it mean you want to see the latest cache as long as you open the list?
If so, I could implement it for you. :)

---

Or maybe we could provide two version of UI for users, and users could select it in the options page of add-on?

**Comment by rayman89** [comment]
Yes a quick popup like before which shows you the latest cache first. Opening a window having to wait for it to load then clicking on show and only then being able to copy the desired text takes too much time compared with before so if we have available two buttons and one is an icon that is easy at hand I figure that icon on the url bar should offer a quicker alternative to the full featured window (that would show pressing the other button).

**Comment by wildskyf** [comment]
I will implement at the v3.4.0 :)
Thanks for your suggestion.

**Comment by wildskyf** [comment]
@rayman89, now you could go to options page in the [about:addons](about:addons), and find your fast access popup back. :)
and, feel free to reopen this issue if you still have problems. :)

**Comment by rayman89** [comment]
thanks a lot
