### ISSUE TITLE
Cursor disappear

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/TextareaCache#51]
Sometimes this add-on would make text cursor in textarea disappear, don't know how to solve it…

**Comment by awendland** [comment]
I've had this issue occur several times for me in FF 57 prior to having the add-on installed. I wonder if this is actually the add-ons fault, or if this is a general FF bug.

**Comment by wildskyf** [comment]
I found that I still have this problem when textarea cache is disabled. So maybe this is a general FF bug. Thank you @awendland
