### ISSUE TITLE
TextareaCache breaks Redmine quoting-feature

### ISSUE THREAD

**Issue by mhartung** [wildskyf/TextareaCache#54]
Required:
* System OS: macOS 10.12.6
* Firefox version: 57 Quantum
* Addon-version: 3.3.0

Optional:
* Create or open an existing redmine (redmine.org) ticket.
* Click on quote, to reply by quoting a user.

Expected:
* The comment text from the user you decided to quote will be shown in your reply.
"> Lorem ipsum dolor sit amet"

Reality:
* The reply field stays empty. But a js-error will be thrown.

Testcase (that expects a login nontheless):
* http://www.hostedredmine.com/issues/714500

`Error: Permission denied to access property "apply" 
jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3:7558
trigger
https://redmine.dkd.de/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3:7558
trigger/<
https://redmine.dkd.de/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3:15396
each
https://redmine.dkd.de/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2:2971
each
https://redmine.dkd.de/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2:833
trigger
https://redmine.dkd.de/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3:15375
m.fn[b]
https://redmine.dkd.de/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4:15178
warnLeavingUnsaved/window.onbeforeunload
https://redmine.dkd.de/javascripts/application.js:736:5
onReload/<
resource://devtools/server/actors/tab.js:989:7
exports.makeInfallible/<
resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14`

**Comment by wildskyf** [comment]
ok, I have solved it.
It will not happen in the latest version, v3.5.0.

I will close this issue when v3.5.0 is released.

**Comment by mhartung** [comment]
Awesome. :)
