### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by wwqq33** [wildskyf/TextareaCache#56]
求中文语言包支持[Seeking Chinese language package support]

我不认识英文，求增加中文语言包。
I do not know English, I hope to increase the Chinese language packs. Google machine translation of English

**Comment by wildskyf** [comment]
好，等我～～～
我週末若有空就會弄，不然就到下週末了！

**Comment by wwqq33** [comment]
好的 谢谢 @wildskyf

**Comment by wildskyf** [comment]
v3.6.0 開始支援中文！

https://github.com/wildskyf/TextareaCache/blob/master/_locales/zh_CN/messages.json
歡迎建議更好的文字 :)
