### ISSUE TITLE
review in Amazon not recorded

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/TextareaCache#57]
I didn't buy anything on Amazon, could someone help me?

**Comment by leo424y** [comment]
<img width="1440" alt="screen shot 2017-12-23 at 2 40 28 pm" src="https://user-images.githubusercontent.com/1384394/34317711-6e8657ca-e7ef-11e7-8fe3-9b867241af14.png">
Here is my review test. It seems works.

**Comment by wildskyf** [comment]
@leo424y thanks a lot!!
