### ISSUE TITLE
v3.9.0 broke it

### ISSUE THREAD

**Issue by Gitoffthelawn** [wildskyf/TextareaCache#60]
Everything worked perfectly until v3.9.0 on FF v58.0beta12 (Windows 7).  Now clicking on "View your saved data (Textarea cache)" does not do anything.

**Comment by wildskyf** [comment]
Hi @Gitoffthelawn ,
you could downgrade old version textarea cache here:
https://addons.mozilla.org/zh-TW/firefox/addon/textarea-cache/versions/

Do you mean the toolbar one(right, colorful) or the urlbar one(left, black and white)?
![2017-12-20 15 14 54](https://user-images.githubusercontent.com/6042803/34195451-8efed710-e598-11e7-8724-3492a84e2b71.png)

**Comment by wildskyf** [comment]
And before you downgrade, could you please restart firefox and see whether it still happen?

**Comment by Gitoffthelawn** [comment]
I mean the toolbar one, but I keep it in the overflow menu (double-right-chevron on the right-end of the toolbar).

I tried restarting the browser, but did not help.

**Comment by wildskyf** [comment]
@Gitoffthelawn Could you please provide your setting in the preference page of Textarea Cache?
And try to modify them, and see whether it still happens?

**Comment by wildskyf** [comment]
I thought I found the problem, please wait for the v3.9.1 release, which will fix the problem for you. :)

**Comment by Gitoffthelawn** [comment]
v3.9.1 fixed it.  Great job!  Thanks! :)
