### ISSUE TITLE
Order by time desc

### ISSUE THREAD

**Issue by lilydjwg** [wildskyf/TextareaCache#61]
/* Thanks for your report! Please provide these info when you found bugs. */

Required:
* System OS: Arch Linux
* Firefox version: 59.0a1 (2017-11-29) (64 位)
* TCL version: 3.12.0

目前显示的是按时间正序排列的，但一般打开列表页面，都是找刚刚输入过的内容的吧，所以倒序会更好一些。

PS: 更新里没写说明啊，经常更新但是不知道更新了什么。
PPS: 上边的 TCL 让我一愣，还以为是问我系统上安装的 tcl shell 的版本……
PPPS: GitHub 项目主页那个链接，可以把「en-US/」去掉，这样会跳转到用户在火狐里指定的语言。

**Comment by wildskyf** [comment]
感謝回報，

我一直想讓他倒序，我在某個 function 中做了，但沒反應 ~.~
下次有大塊時間時來查

PS-res: 我打算開一個頁面來寫 changelog，之後更新時就會寫更新了什麼～
PSS-res: 以前叫 Textarea Cache Lite，所以才簡寫 tcl，等等去把它改成現在的全名
PSSS-res: 好，感謝建議！

**Comment by wildskyf** [comment]
v3.13.0 應該會是倒序的了～再麻煩你幫我測測看囉！

**Comment by lilydjwg** [comment]
我不知道是不是倒序了，因为都是「Invalid Date」……

**Comment by wildskyf** [comment]
WTF... 我去看看⋯⋯

**Comment by wildskyf** [comment]
奇怪，可以麻煩你幫我截個圖嗎@@

**Comment by lilydjwg** [comment]
![textcache](https://user-images.githubusercontent.com/440661/34460971-40c7443c-ee59-11e7-8f62-546e2b0d00cc.png)

**Comment by DirkSchmitt** [comment]
**Please provide (minimal) bug description in English as *Lingua Franca* to avoid duplicated bug reports.**

Is this bug concerning a reverse time ordering of the text entries ?

**Comment by lilydjwg** [comment]
@DirkSchmitt yes. A minimal description is there (the title).

**Comment by bendover22** [comment]
I see the same problem.  Before Nov. 16, 2017, TAC shows all entries "Invalid Date."  It's now Jan, 12, 2018.  
I'm using Fx 52.5.3 ESR, in Mint 18.1 64 bit.
So the bulk of save text entries show invalid dates.  The Invalid Date entries do show the URL & the 1st line of text.

Also, the order of saved entries is the reverse of what most users would need (probably already mentioned).
The oldest are listed 1st, and you have to scroll WAY to the bottom to see the latest one (which  most likely is the one that users would need more often.  Not entries from months ago.

**Comment by wildskyf** [comment]
I just update a new version, which would solve the delete bug and Invalid Date problem.
Please help me test, thx!

**Comment by wildskyf** [comment]
> PS: 更新里没写说明啊，经常更新但是不知道更新了什么。

後來發現更新新套件時，AMO 上有個可以填版本更新的欄位，但在 US 之外的語言下有問題（textarea 框顯示不出來），在我弄出一個版本更新 board 之前我會先寫在那裡～

如果跳了版號，也可以來這兒看 update log
https://addons.mozilla.org/zh-TW/firefox/addon/textarea-cache/versions/

**Comment by lilydjwg** [comment]
对，amo 有这么个 bug： https://github.com/mozilla/addons-server/issues/4599

我把旧数据清掉了再试了试，暂时没有发现问题了。

**Comment by wildskyf** [comment]
good.
This bug should have been solved in v3.15.0.
Feel free to reopen this issue or open another issue if you still have any question.
