### ISSUE TITLE
Not enough window size adjustment ability

### ISSUE THREAD

**Issue by bendover22** [wildskyf/TextareaCache#71]
/* Thanks for your report! Please provide these info when you found bugs. */

Required:
* System OS: Mint 18.1
Firefox version: 52.7.2esr
* Textarea Cache version: 3.17.0

Optional:
*Open the Text Area Cache icon / window.
*The lower message pane  is fairly short - vertically.  That's OK for short messages.  Scroll bars do appear if the message is longer than the display pane - that's good.  Sometimes it's much easier to view a whole paragraph, etc., at once,  instead of a few lines.
Even if you lengthen TACL's whole UI, the message display pane barely increases in height.  Grabbing the lower, corner resize grip doesn't help this.
** Maybe the dividing line between the upper / lower pane should be draggable?

** It also doesn't remember the (small) resizing I did the last time I opened TACL.  Neither the entire UI size or the message pane height.  It probably should remember both.

** Different issue - but it's strange.  If you leave the TACL window open while typing in the browser (text box), the TACL UI flashes / pulsates.  A lot.  The text display totally blanks out with each keystroke, then reappears.  If you type fast, it flashes fast.  You don't want to look at this for long or it might cause motion sickness.

**Comment by bendover22** [comment]
You should close this - I guess.  It's no longer a problem for me, unless others still have this issue.  Wanted to check before I hit "closed." 
Maybe in other OSes or diff Linux distros than Mint?

**Comment by wildskyf** [comment]
thx!
If you no longer face this problem, we could happily close this issue.

If there is anyone who has this problem, please re-open it. :)
