### ISSUE TITLE
Question: where are the version changes_don't see any on AMO

### ISSUE THREAD

**Issue by bendover22** [wildskyf/TextareaCache#74]
Required:
* System OS: (e.g., Fedora 26)
* Firefox version: (e.g., Firefox 56.0)
* Textarea Cache version: (e.g., 2.5.0)
Mint 18.1; Firefox 52.7.2 x86_64
TACL 3.19.5

Where are the changes for each TACL release, as mentioned on this Github site?
I see a long list of versions on AMO, but no changes or links to change logs.
Don't see changes by version on this Github site, either.
If we can't see a change list in each release, we can't tell if the changes are working.

I looked at the page source for AMO / TACL's releases.  Nothing there about fixes, changes or change logs.  I re-checked today, when I saw a TACL update was available.  Am I missing something that everyone else can see?

I noticed this several versions ago - didn't have time to ask until now.

**Comment by wildskyf** [comment]
Hi @bendover22 

Thank you fir your kind question. And here is the answer you are looking for: https://addons.mozilla.org/firefox/addon/textarea-cache/versions/ , which is also the page you mentioned in your question.

Actually, there is no change log information in that page is because I don't know weather my users care and also... I am too lazy... (Sorry about that). ;P

I will write the changes down on that page if you want. Really thank you for your request, which tell me that my users do care what I update. :)

**Comment by bendover22** [comment]
One reason change logs can be useful is after an update, if problems start, knowing what changed in different addons may give some clue what's causing it.  Sometimes not, but it's better than having no information.

**Comment by Gitoffthelawn** [comment]
I appreciate your changelogs!

**Comment by bendover22** [comment]
Time flies when we're having fun!
Four yrs after 1st asked, & still don't see any release notes / changes.  Not on AMO or Github.
Maybe not everyone reads release notes, but quite a few do.

I don't use 100's of addons but it's hard to remember many that didn't make release notes available - somewhere.
Am I missing something?  In the latest code changes (manifest.json - couple days ago), it shows line 11 changing:
```
-  "version": "4.3.0",
+  "version": "4.4.0"
 ```
Isn't it supposed to be for version 4.5.0, or am I misinterpreting?

**Comment by wildskyf** [comment]
@bendover22 It is 4.5.0.
I just forgot to git push onto GitHub my commits yesterday...

the v4.5.0 contains these changes:
- Remove tabs permission
- stop using amo link as add-on homepage

And I just add them to version page on amo for v4.5.0: https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/versions/
