### ISSUE TITLE
Make the data save interval configurable

### ISSUE THREAD

**Issue by birdie-github** [wildskyf/TextareaCache#78]
I'm not sure I've read the sources correctly but I've noticed that the data save interval is hardcoded and it's 2 seconds. 2 seconds might be detrimental if you're editing a large text and you have an SSD disk.

Please, expose this interval in add-on settings and let the user configure it (in milliseconds).

Allowing the user to enter "0" is probably not a good idea.

**Comment by wildskyf** [comment]
Hi @birdie-github,
you could configure it in the option page.

<img width="748" alt="2019-01-27 20 34 37" src="https://user-images.githubusercontent.com/6042803/51800994-090de600-2273-11e9-9309-ccb076a3a8ac.png">

Feel free to reopen issue if you still get any problem.
