### ISSUE TITLE
Allow access to options from dropdown panel when cache empty

### ISSUE THREAD

**Issue by Gitoffthelawn** [wildskyf/TextareaCache#83]
When there is text in the cache, it's easy to access TextareaCache's options panel from it's toolbar button dropdown (hit the cog icon).  But once the user empties the cache, the cog icon disappears.  Can you make it visible in all cases?

**Comment by wildskyf** [comment]
yeah, I will fix it for version 4.2.0
thanks for the issue. :)

**Comment by Gitoffthelawn** [comment]
Thanks!
