### ISSUE TITLE
Update project homepage with Chrome version link

### ISSUE THREAD

**Issue by 4evermaat** [wildskyf/TextareaCache#89]
Can you update the [project homepage](https://github.com/wildskyf/TextareaCache) with the Chrome link?  

https://chrome.google.com/webstore/detail/textarea-cache/chpphekfimlabghbdankokcohcmnbmab

Also you should edit your bug template to ask the user for Chrome or Firefox browser.

**Comment by wildskyf** [comment]
@4evermaat Sure, and thx for your suggestion.
